### ISSUE TITLE
README -  Websocket API Example

### ISSUE THREAD

**Issue by RomainRouphael** [ln-markets/api-js#112]
I think the code example should be updated as follows after the latest release:

import { createWebsocketClient } from '@ln-markets/api'
// Need to be async
const client = await createWebsocketClient()

**await client.publicSubscribe(['futures:btc_usd:last-price', 'futures:btc_usd:index'])**

// Event on all response
**client.ws.on('response', console.log)**
// Event emitter on subscribed channels
**client.ws.on('futures:btc_usd:last-price', console.log)
client.ws.on('futures:btc_usd:index', console.log)**

// Handle websocket error here
client.ws.on('error', console.error)

**Comment by vafanassieff** [comment]
Fixed the doc, it took a while !
