### ISSUE TITLE
[ERROR] 22:02:22 LNMarketsRestError: Signature is not valid

### ISSUE THREAD

**Issue by mrWiga** [ln-markets/api-js#17]
NMarketsRest {
  key: 'xxxx+o5kB8=',
  secret: 'xxxx=',
  passphrase: 'xxxxx',
  network: 'testnet',
  version: 'v1',
  hostname: 'api.testnet.lnmarkets.com',
  customHeaders: {},
  fullResponse: undefined,
  debug: false,
  skipApiKey: undefined
}
LNMarketsRestError: Signature is not valid
    at IncomingMessage.<anonymous> (/Users/Projects/nodejs/lnmarkets/node_modules/@ln-markets/api/src/rest.js:146:22)
    at IncomingMessage.emit (node:events:381:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21)
[ERROR] 22:02:22 LNMarketsRestError: Signature is not valid

When I execute the following function
```
import "../lib/env";
import { LNMarketsRest } from "@ln-markets/api";
const lnm = new LNMarketsRest();

async function test() {
  console.log(lnm);
  await lnm.depositHistory({
    limit: 1,
  });
}

test();

```

This function is working for me:
```
await lnm.futuresGetPositions({ type: "closed" });
```

So it's not API KEY, secret, phase etc.

**Comment by vafanassieff** [comment]
Fixed in v1.5.2 !
